# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               » Râu Bắp
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://rau.us.to
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Râu Bắp
  url:               http://rau.us.to
  email:             ng.hung83@gmail.com

# Custom vars
version:             1.0.0
